package interfaz;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;

import javax.swing.ImageIcon;
import javax.swing.JComboBox;

import uniandes.dpoo.taller4.modelo.Tablero;

/**
*
* @author ASUS
*/
public class VentGUI extends javax.swing.JFrame {
	
   int tamano = 5;
   
   Image img;
   boolean imagen1;
   
   /**
    * Creates new form VentGUI
    */
   public VentGUI() {
       initComponents();
       
       img = new ImageIcon("data/luz.png").getImage();
   }

   public void ponertablero(Graphics g) {
	   Graphics2D g2D = (Graphics2D) g;  
	   
	   imagen1 = g2D.drawImage(img, 0, 0, null);
	   
	  
	   
	   
   }
	
   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
   private void initComponents() {

       jPanel4 = new javax.swing.JPanel(); 
       panelTop = new javax.swing.JPanel();
       radioFacil = new javax.swing.JRadioButton();
       radioMedio = new javax.swing.JRadioButton();
       radioDificil = new javax.swing.JRadioButton();
       labelDificultad = new javax.swing.JLabel();
       labelTamano = new javax.swing.JLabel();
       cajaTamanos = new javax.swing.JComboBox<>();
       panelTablero = new javax.swing.JPanel();
       panelBotones = new javax.swing.JPanel();
       botonNuevo = new javax.swing.JButton();
       botonReiniciar = new javax.swing.JButton();
       botonTop = new javax.swing.JButton();
       botonCambiarJugador = new javax.swing.JButton();
       panelBot = new javax.swing.JPanel();
       labelJugadas = new javax.swing.JLabel();
       labelJugador = new javax.swing.JLabel();

       javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
       jPanel4.setLayout(jPanel4Layout);
       jPanel4Layout.setHorizontalGroup(
           jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGap(0, 100, Short.MAX_VALUE)
       );
       jPanel4Layout.setVerticalGroup(
           jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGap(0, 100, Short.MAX_VALUE)
       );

       setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
       setBackground(new java.awt.Color(0, 0, 0));

       panelTop.setBackground(new java.awt.Color(239, 233, 231));

       radioFacil.setText("Fácil");
       radioFacil.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               radioFacilActionPerformed(evt);
           }
       });

       radioMedio.setText("Medio");

       radioDificil.setText("Dificil");
       radioDificil.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               radioDificilActionPerformed(evt);
           }
       });

       labelDificultad.setText("Dificultad:");

       labelTamano.setText("Tamaño:");

       cajaTamanos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5x5", "6x6", "7x7", "8x8" }));
       cajaTamanos.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
        	   
        	   cajaTamanosActionPerformed(evt);
           }
       });

       javax.swing.GroupLayout panelTopLayout = new javax.swing.GroupLayout(panelTop);
       panelTop.setLayout(panelTopLayout);
       panelTopLayout.setHorizontalGroup(
           panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTopLayout.createSequentialGroup()
               .addGap(47, 47, 47)
               .addComponent(labelTamano)
               .addGap(18, 18, 18)
               .addComponent(cajaTamanos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(labelDificultad, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addGap(24, 24, 24)
               .addComponent(radioFacil)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
               .addComponent(radioMedio)
               .addGap(12, 12, 12)
               .addComponent(radioDificil)
               .addContainerGap())
       );
       panelTopLayout.setVerticalGroup(
           panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(panelTopLayout.createSequentialGroup()
               .addGroup(panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(radioFacil)
                   .addComponent(radioMedio)
                   .addComponent(radioDificil)
                   .addComponent(labelDificultad)
                   .addComponent(labelTamano)
                   .addComponent(cajaTamanos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGap(0, 6, Short.MAX_VALUE))
       );
       
       grupoBotonesTop.add(radioFacil);
       grupoBotonesTop.add(radioMedio);
       grupoBotonesTop.add(radioDificil);
       
       
       //Panel del tablero
          
       int i, j;
       panelTablero.setBackground(new java.awt.Color(239, 233, 231));
       
       
       Tablero miTablero = new Tablero(tamano);
       
       miTablero.darTablero();
       
       javax.swing.GroupLayout panelTableroLayout = new javax.swing.GroupLayout(panelTablero);
       panelTablero.setLayout(panelTableroLayout);
       panelTableroLayout.setHorizontalGroup(
           panelTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGap(0, 466, Short.MAX_VALUE)
           
           
       );
       panelTableroLayout.setVerticalGroup(
           panelTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGap(0, 428, Short.MAX_VALUE)
       );
       
       
       //Cierre panel del tablero
       panelBotones.setBackground(new java.awt.Color(239, 233, 231));

       botonNuevo.setBackground(java.awt.SystemColor.inactiveCaptionBorder);
       botonNuevo.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
       botonNuevo.setText("NUEVO");
       botonNuevo.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               botonNuevoActionPerformed(evt);
           }
       });

       botonReiniciar.setBackground(java.awt.SystemColor.inactiveCaptionBorder);
       botonReiniciar.setText("REINICIAR");
       botonReiniciar.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               botonReiniciarActionPerformed(evt);
           }
       });

       botonTop.setBackground(java.awt.SystemColor.inactiveCaptionBorder);
       botonTop.setText("TOP-10");
       botonTop.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               botonTopActionPerformed(evt);
           }
       });

       botonCambiarJugador.setBackground(java.awt.SystemColor.inactiveCaptionBorder);
       botonCambiarJugador.setText("CAMBAIR JUGADOR");

       javax.swing.GroupLayout panelBotonesLayout = new javax.swing.GroupLayout(panelBotones);
       panelBotones.setLayout(panelBotonesLayout);
       panelBotonesLayout.setHorizontalGroup(
           panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(panelBotonesLayout.createSequentialGroup()
               .addContainerGap()
               .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addComponent(botonNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                   .addComponent(botonReiniciar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                   .addComponent(botonTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                   .addComponent(botonCambiarJugador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
               .addContainerGap())
       );
       panelBotonesLayout.setVerticalGroup(
           panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(panelBotonesLayout.createSequentialGroup()
               .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(botonNuevo)
               .addGap(18, 18, 18)
               .addComponent(botonReiniciar)
               .addGap(18, 18, 18)
               .addComponent(botonTop)
               .addGap(18, 18, 18)
               .addComponent(botonCambiarJugador)
               .addGap(152, 152, 152))
       );

       panelBot.setBackground(new java.awt.Color(239, 233, 231));

       labelJugadas.setText("Jugadas: 0");

       labelJugador.setText("Jugador:");

       javax.swing.GroupLayout panelBotLayout = new javax.swing.GroupLayout(panelBot);
       panelBot.setLayout(panelBotLayout);
       panelBotLayout.setHorizontalGroup(
           panelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(panelBotLayout.createSequentialGroup()
               .addContainerGap()
               .addComponent(labelJugadas, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addGap(164, 164, 164)
               .addComponent(labelJugador)
               .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
       );
       panelBotLayout.setVerticalGroup(
           panelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBotLayout.createSequentialGroup()
               .addContainerGap(8, Short.MAX_VALUE)
               .addGroup(panelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(labelJugadas)
                   .addComponent(labelJugador))
               .addContainerGap())
       );

       javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
       getContentPane().setLayout(layout);
       layout.setHorizontalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
           .addComponent(panelTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
           .addGroup(layout.createSequentialGroup()
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addComponent(panelBot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                   .addComponent(panelTablero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addComponent(panelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
       );
       layout.setVerticalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addComponent(panelTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addGroup(layout.createSequentialGroup()
                       .addComponent(panelTablero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                       .addComponent(panelBot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                   .addComponent(panelBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
       );

       pack();
   }// </editor-fold>                        

   private void botonReiniciarActionPerformed(java.awt.event.ActionEvent evt) {                                               
       // TODO add your handling code here:
   }                                              

   private void botonNuevoActionPerformed(java.awt.event.ActionEvent evt) {                                           
       // TODO add your handling code here:
   }                                          

   private void botonTopActionPerformed(java.awt.event.ActionEvent evt) {                                         
       // TODO add your handling code here:
   }                                        

   private void radioFacilActionPerformed(java.awt.event.ActionEvent evt) {                                           
       // TODO add your handling code here:
   }                                          

   private void radioDificilActionPerformed(java.awt.event.ActionEvent evt) {                                             
       // TODO add your handling code here:
   }                                            

   private void cajaTamanosActionPerformed(java.awt.event.ActionEvent evt) {                                            
       // TODO add your handling code here:
	   
	   JComboBox<String> cajaTamanos = (JComboBox<String>) evt.getSource();
       Object selected = cajaTamanos.getSelectedItem();
       if(selected.toString().equals("5x5")) 
    	   tamano = 5;
       else if(selected.toString().equals("6x6"))
           tamano = 6;
       else if(selected.toString().equals("7x7"))
           tamano = 7;
       else if(selected.toString().equals("8x8"))
           tamano = 8;
       else 
    	   tamano = 5;
       
       
       
   }
   

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
       /* Set the Nimbus look and feel */
       //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
       /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
        */
       
	   
	

       try {
           for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
               if ("Nimbus".equals(info.getName())) {
                   javax.swing.UIManager.setLookAndFeel(info.getClassName());
                   break;
               }
           }
       } catch (ClassNotFoundException ex) {
           java.util.logging.Logger.getLogger(VentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (InstantiationException ex) {
           java.util.logging.Logger.getLogger(VentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (IllegalAccessException ex) {
           java.util.logging.Logger.getLogger(VentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (javax.swing.UnsupportedLookAndFeelException ex) {
           java.util.logging.Logger.getLogger(VentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       }
       
       java.awt.EventQueue.invokeLater(new Runnable() {
           public void run() {
               new VentGUI().setVisible(true);
           }
       });
   }

   private Tablero miTablero;                   
   private javax.swing.JButton botonCambiarJugador;
   private javax.swing.JButton botonNuevo;
   private javax.swing.JButton botonReiniciar;
   private javax.swing.JButton botonTop;
   private javax.swing.ButtonGroup grupoBotonesTop;
   private javax.swing.JComboBox<String> cajaTamanos;
   private javax.swing.JPanel jPanel4;
   private javax.swing.JLabel labelDificultad;
   private javax.swing.JLabel labelJugadas;
   private javax.swing.JLabel labelJugador;
   private javax.swing.JLabel labelTamano;
   private javax.swing.JPanel panelBot;
   private javax.swing.JPanel panelBotones;
   private javax.swing.JPanel panelTablero;
   private javax.swing.JPanel panelTop;
   private javax.swing.JRadioButton radioDificil;
   private javax.swing.JRadioButton radioFacil;
   private javax.swing.JRadioButton radioMedio;
                    
}

